CREATE TABLE MARKS
(
ID INT IDENTITY(1,1) NOT NULL,
MARK INT NOT NULL,
STUDENTID INT,
PRIMARY KEY (ID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENT(ID)
);

SELECT s.FIRSTNAME, s.LASTNAME, g.GROUPNAME, AVG(m.MARK) AS AVERANGE
FROM STUDENT s
JOIN MARKS m ON s.ID = m.STUDENTID
JOIN GROUPS g ON s.GROUPSID = g.ID
GROUP BY s.FIRSTNAME, s.LASTNAME, g.GROUPNAME
HAVING AVG(AVERANGE) = 
(
  SELECT MAX(AVERAGE)
  FROM
  (
    SELECT AVG(m.MARK) AS AVERAGE
    FROM STUDENT s
    JOIN MARKS m ON s.ID = m.STUDENTID
    JOIN GROUPS g ON s.GROUPSID = g.ID
    WHERE s.GROUPSID = g.ID
    GROUP BY s.ID
  ) AS student_averages
)


