CREATE TABLE GROUPS
(
ID INT IDENTITY(1,1) NOT NULL,
GROUPNAME NCHAR(15) NOT NULL,
GROUPCURSE INT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE STUDENT
(
ID INT IDENTITY(1,1) NOT NULL,
FIRSTNAME NCHAR(15) NOT NULL,
LASTNAME NCHAR(15) NOT NULL,
GROUPSID INT,
PRIMARY KEY (ID),
FOREIGN KEY (GROUPSID) REFERENCES GROUPS(ID)
);


INSERT INTO GROUPS (GROUPNAME, GROUPCURSE) VALUES ('ECONOMICS', 1);
INSERT INTO GROUPS (GROUPNAME, GROUPCURSE) VALUES ('MECHANICS', 2);
INSERT INTO GROUPS (GROUPNAME, GROUPCURSE) VALUES ('PROGRAMMERS', 3);

INSERT INTO STUDENT (FIRSTNAME, LASTNAME, GROUPSID) VALUES ('IVAN', 'IVANOV', 1);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, GROUPSID) VALUES ('PETR', 'PETROV', 1);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, GROUPSID) VALUES ('SIDOR', 'SIDOROV', 2);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, GROUPSID) VALUES ('ALBERT', 'KOZLOV', 2);
INSERT INTO STUDENT (FIRSTNAME, LASTNAME) VALUES ('MAXIM', 'KAMNEV');

SELECT * 
FROM STUDENT S
JOIN GROUPS G 
ON S.GROUPSID = G.ID
WHERE S.FIRSTNAME = 'ALBERT';

DELETE FROM STUDENT 
WHERE GROUPSID IS NULL;

UPDATE GROUPS
SET GROUPCURSE = GROUPCURSE + 1;
